/** Indian states / UTs. `value` is what we store; `hi` is the label shown on the Hindi site. */
export const STATE_LIST: { value: string; hi: string }[] = [
  { value: 'Andaman and Nicobar Islands', hi: 'अंडमान और निकोबार द्वीप समूह' },
  { value: 'Andhra Pradesh', hi: 'आंध्र प्रदेश' },
  { value: 'Arunachal Pradesh', hi: 'अरुणाचल प्रदेश' },
  { value: 'Assam', hi: 'असम' },
  { value: 'Bihar', hi: 'बिहार' },
  { value: 'Chandigarh', hi: 'चंडीगढ़' },
  { value: 'Chhattisgarh', hi: 'छत्तीसगढ़' },
  { value: 'Dadra and Nagar Haveli and Daman and Diu', hi: 'दादरा और नगर हवेली तथा दमन और दीव' },
  { value: 'Delhi', hi: 'दिल्ली' },
  { value: 'Goa', hi: 'गोवा' },
  { value: 'Gujarat', hi: 'गुजरात' },
  { value: 'Haryana', hi: 'हरियाणा' },
  { value: 'Himachal Pradesh', hi: 'हिमाचल प्रदेश' },
  { value: 'Jammu and Kashmir', hi: 'जम्मू और कश्मीर' },
  { value: 'Jharkhand', hi: 'झारखंड' },
  { value: 'Karnataka', hi: 'कर्नाटक' },
  { value: 'Kerala', hi: 'केरल' },
  { value: 'Ladakh', hi: 'लद्दाख' },
  { value: 'Lakshadweep', hi: 'लक्षद्वीप' },
  { value: 'Madhya Pradesh', hi: 'मध्य प्रदेश' },
  { value: 'Maharashtra', hi: 'महाराष्ट्र' },
  { value: 'Manipur', hi: 'मणिपुर' },
  { value: 'Meghalaya', hi: 'मेघालय' },
  { value: 'Mizoram', hi: 'मिज़ोरम' },
  { value: 'Nagaland', hi: 'नागालैंड' },
  { value: 'Odisha', hi: 'ओडिशा' },
  { value: 'Puducherry', hi: 'पुदुचेरी' },
  { value: 'Punjab', hi: 'पंजाब' },
  { value: 'Rajasthan', hi: 'राजस्थान' },
  { value: 'Sikkim', hi: 'सिक्किम' },
  { value: 'Tamil Nadu', hi: 'तमिलनाडु' },
  { value: 'Telangana', hi: 'तेलंगाना' },
  { value: 'Tripura', hi: 'त्रिपुरा' },
  { value: 'Uttar Pradesh', hi: 'उत्तर प्रदेश' },
  { value: 'Uttarakhand', hi: 'उत्तराखंड' },
  { value: 'West Bengal', hi: 'पश्चिम बंगाल' },
]
export const stateLabel = (value: string | null | undefined, lang: 'hi' | 'en') =>
  !value ? '' : lang === 'hi' ? (STATE_LIST.find((s) => s.value === value)?.hi ?? value) : value
