/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    categories: Category;
    tags: Tag;
    authors: Author;
    'breaking-news': BreakingNew;
    corrections: Correction;
    pages: Page;
    media: Media;
    submissions: Submission;
    appointments: Appointment;
    'contact-messages': ContactMessage;
    'private-files': PrivateFile;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'breaking-news': BreakingNewsSelect<false> | BreakingNewsSelect<true>;
    corrections: CorrectionsSelect<false> | CorrectionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'private-files': PrivateFilesSelect<false> | PrivateFilesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('hi' | 'en') | ('hi' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'hi' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Reporters save drafts and set Review status → "Submitted". Only Editors/Admins can publish. Future publish date = scheduled.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * 1–2 line summary for cards and SEO
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Sources shown in the "Sources & documents" box
   */
  sources?:
    | {
        label: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  factCheck?: {
    /**
     * The claim being checked
     */
    claim?: string | null;
    /**
     * Where / by whom the claim was made
     */
    claimedBy?: string | null;
    verdict?: ('true' | 'false' | 'misleading' | 'unverified') | null;
  };
  /**
   * Template: Issue → Facts → Documents → Response → Ground reality → Public questions → Answer → Follow-up
   */
  investigation?: {
    issue?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    facts?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    documents?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    response?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    groundReality?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    publicQuestions?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    answer?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    followUp?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * समस्या → शिकायत → संबंधित विभाग → जवाब → कार्रवाई → परिणाम
   */
  tracker?:
    | {
        stage: 'problem' | 'complaint' | 'department' | 'response' | 'action' | 'result';
        date?: string | null;
        status?: ('done' | 'progress' | 'pending') | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as a badge on "Direct Question to Government" stories
   */
  questionStatus?: ('asked' | 'responded' | 'action') | null;
  /**
   * Ministry / department / official asked
   */
  askedTo?: string | null;
  /**
   * If this is a "Response received" / "Action taken" story, link the original question here. Links show on both pages.
   */
  followUpOf?: (number | null) | Article;
  /**
   * Documents Speak: attach PDFs/images with source and reference
   */
  documents?:
    | {
        file: number | Media;
        title?: string | null;
        /**
         * e.g. RTI reply, Govt order, Court record
         */
        source?: string | null;
        /**
         * Letter no. / RTI no. / date
         */
        reference?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL. Blank = auto from title. Roman letters recommended (e.g. kisan-mandi-bhav).
   */
  slug?: string | null;
  format: 'news' | 'factcheck' | 'investigation' | 'question' | 'tracker' | 'documents' | 'opinion';
  category: number | Category;
  tags?: (number | Tag)[] | null;
  author?: (number | null) | Author;
  /**
   * Future date = scheduled; goes live automatically.
   */
  publishedAt: string;
  heroImage?: (number | null) | Media;
  /**
   * Only for freely-licensed hotlinked images (Wikimedia/Unsplash). Credit is required.
   */
  externalImage?: {
    url?: string | null;
    credit?: string | null;
    creditUrl?: string | null;
  };
  featured?: boolean | null;
  reviewStatus?: ('draft' | 'submitted' | 'changes' | 'approved') | null;
  legalReviewed?: boolean | null;
  sample?: boolean | null;
  /**
   * Temporary demo item. Bulk delete: npm run demo:remove
   */
  demoContent?: boolean | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images and public documents (PDF). Always fill credit + licence for third-party files.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * e.g. "Photo: Jane Doe / Unsplash"
   */
  credit?: string | null;
  creditUrl?: string | null;
  /**
   * e.g. CC BY-SA 4.0, Unsplash License, Own
   */
  license?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL. Blank = auto from title. Roman letters recommended (e.g. kisan-mandi-bhav).
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Set for sub-categories
   */
  parent?: (number | null) | Category;
  /**
   * Main menu position (lower = first). Sub-categories are ordered the same way.
   */
  menuOrder?: number | null;
  showInMenu?: boolean | null;
  /**
   * Column in the desktop mega-menu
   */
  menuGroup?: ('news' | 'accountability' | 'public' | 'people') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  /**
   * URL. Blank = auto from title. Roman letters recommended (e.g. kisan-mandi-bhav).
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * URL. Blank = auto from title. Roman letters recommended (e.g. kisan-mandi-bhav).
   */
  slug?: string | null;
  designation?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  /**
   * Linked login (optional)
   */
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'reporter';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breaking-news".
 */
export interface BreakingNew {
  id: number;
  text: string;
  /**
   * Optional, e.g. /hi/news/some-slug
   */
  link?: string | null;
  active?: boolean | null;
  expiresAt?: string | null;
  demoContent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections".
 */
export interface Correction {
  id: number;
  article: number | Article;
  type?: ('correction' | 'clarification' | 'update') | null;
  date: string;
  /**
   * What was wrong and what was corrected
   */
  summary: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL. Blank = auto from title. Roman letters recommended (e.g. kisan-mandi-bhav).
   */
  slug?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  legalReviewPending?: boolean | null;
  showInFooter?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  anonymous?: boolean | null;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  state?: string | null;
  district?: string | null;
  location?: string | null;
  issueType?: string | null;
  department?: string | null;
  subject?: string | null;
  description?: string | null;
  complaintFiled?: string | null;
  complaintRef?: string | null;
  files?: (number | PrivateFile)[] | null;
  referenceId?: string | null;
  status?: ('new' | 'verifying' | 'story-in-progress' | 'published' | 'closed' | 'spam') | null;
  internalNotes?: string | null;
  consentAt?: string | null;
  lang?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Files attached by citizens. Not publicly accessible.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-files".
 */
export interface PrivateFile {
  id: number;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: number;
  name?: string | null;
  organisation?: string | null;
  phone?: string | null;
  email?: string | null;
  state?: string | null;
  city?: string | null;
  meetingWith?: string | null;
  purpose?: string | null;
  preferredDate?: string | null;
  preferredTime?: string | null;
  mode?: string | null;
  message?: string | null;
  referenceId?: string | null;
  status?: ('new' | 'confirmed' | 'rescheduled' | 'declined' | 'done') | null;
  internalNotes?: string | null;
  consentAt?: string | null;
  lang?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  topic?: string | null;
  subject?: string | null;
  message?: string | null;
  referenceId?: string | null;
  status?: ('new' | 'replied' | 'closed' | 'spam') | null;
  internalNotes?: string | null;
  consentAt?: string | null;
  lang?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'breaking-news';
        value: number | BreakingNew;
      } | null)
    | ({
        relationTo: 'corrections';
        value: number | Correction;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'appointments';
        value: number | Appointment;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'private-files';
        value: number | PrivateFile;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  factCheck?:
    | T
    | {
        claim?: T;
        claimedBy?: T;
        verdict?: T;
      };
  investigation?:
    | T
    | {
        issue?: T;
        facts?: T;
        documents?: T;
        response?: T;
        groundReality?: T;
        publicQuestions?: T;
        answer?: T;
        followUp?: T;
      };
  tracker?:
    | T
    | {
        stage?: T;
        date?: T;
        status?: T;
        note?: T;
        id?: T;
      };
  questionStatus?: T;
  askedTo?: T;
  followUpOf?: T;
  documents?:
    | T
    | {
        file?: T;
        title?: T;
        source?: T;
        reference?: T;
        id?: T;
      };
  slug?: T;
  format?: T;
  category?: T;
  tags?: T;
  author?: T;
  publishedAt?: T;
  heroImage?: T;
  externalImage?:
    | T
    | {
        url?: T;
        credit?: T;
        creditUrl?: T;
      };
  featured?: T;
  reviewStatus?: T;
  legalReviewed?: T;
  sample?: T;
  demoContent?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  parent?: T;
  menuOrder?: T;
  showInMenu?: T;
  menuGroup?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  designation?: T;
  bio?: T;
  photo?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breaking-news_select".
 */
export interface BreakingNewsSelect<T extends boolean = true> {
  text?: T;
  link?: T;
  active?: T;
  expiresAt?: T;
  demoContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections_select".
 */
export interface CorrectionsSelect<T extends boolean = true> {
  article?: T;
  type?: T;
  date?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  legalReviewPending?: T;
  showInFooter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  creditUrl?: T;
  license?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  anonymous?: T;
  name?: T;
  phone?: T;
  email?: T;
  state?: T;
  district?: T;
  location?: T;
  issueType?: T;
  department?: T;
  subject?: T;
  description?: T;
  complaintFiled?: T;
  complaintRef?: T;
  files?: T;
  referenceId?: T;
  status?: T;
  internalNotes?: T;
  consentAt?: T;
  lang?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  name?: T;
  organisation?: T;
  phone?: T;
  email?: T;
  state?: T;
  city?: T;
  meetingWith?: T;
  purpose?: T;
  preferredDate?: T;
  preferredTime?: T;
  mode?: T;
  message?: T;
  referenceId?: T;
  status?: T;
  internalNotes?: T;
  consentAt?: T;
  lang?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  topic?: T;
  subject?: T;
  message?: T;
  referenceId?: T;
  status?: T;
  internalNotes?: T;
  consentAt?: T;
  lang?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-files_select".
 */
export interface PrivateFilesSelect<T extends boolean = true> {
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  trustName?: string | null;
  trustRegistrationNo?: string | null;
  /**
   * Editor / Editor-in-chief
   */
  editorName?: string | null;
  publisherName?: string | null;
  /**
   * Any other legal / registration text for the footer
   */
  registrationNote?: string | null;
  address?: string | null;
  email?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  grievanceOfficer?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  /**
   * New submissions / appointments / contact messages are emailed here (falls back to NOTIFY_EMAIL env).
   */
  notifyEmail?: string | null;
  social?: {
    facebook?: string | null;
    x?: string | null;
    youtube?: string | null;
    instagram?: string | null;
    whatsappChannel?: string | null;
    telegram?: string | null;
  };
  /**
   * Placeholder only — ad slots render nothing until built.
   */
  adsEnabled?: boolean | null;
  /**
   * Placeholder only — not built yet.
   */
  donationsEnabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  trustName?: T;
  trustRegistrationNo?: T;
  editorName?: T;
  publisherName?: T;
  registrationNote?: T;
  address?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  grievanceOfficer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  notifyEmail?: T;
  social?:
    | T
    | {
        facebook?: T;
        x?: T;
        youtube?: T;
        instagram?: T;
        whatsappChannel?: T;
        telegram?: T;
      };
  adsEnabled?: T;
  donationsEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}