/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    videos: Video;
    categories: Category;
    tags: Tag;
    authors: Author;
    'team-members': TeamMember;
    'breaking-news': BreakingNew;
    corrections: Correction;
    pages: Page;
    media: Media;
    submissions: Submission;
    appointments: Appointment;
    'contact-messages': ContactMessage;
    'private-files': PrivateFile;
    users: User;
    'audit-log': AuditLog;
    'media-jobs': MediaJob;
    pronunciations: Pronunciation;
    'share-log': ShareLog;
    ads: Ad;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'breaking-news': BreakingNewsSelect<false> | BreakingNewsSelect<true>;
    corrections: CorrectionsSelect<false> | CorrectionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'private-files': PrivateFilesSelect<false> | PrivateFilesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'media-jobs': MediaJobsSelect<false> | MediaJobsSelect<true>;
    pronunciations: PronunciationsSelect<false> | PronunciationsSelect<true>;
    'share-log': ShareLogSelect<false> | ShareLogSelect<true>;
    ads: AdsSelect<false> | AdsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('hi' | 'en') | ('hi' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    permissions: Permission;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
  };
  locale: 'hi' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Tip: the Desk (/desk) is the fast way to add news. Reporters save drafts and set Review status → "Submitted". Only Editors/Admins can publish. Future publish date = scheduled.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Optional second line under the headline
   */
  subheadline?: string | null;
  /**
   * 1–2 line summary for cards and SEO
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Sources shown in the "Sources & documents" box
   */
  sources?:
    | {
        label: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  factCheck?: {
    /**
     * The claim being checked
     */
    claim?: string | null;
    /**
     * Where / by whom the claim was made
     */
    claimedBy?: string | null;
    verdict?: ('true' | 'false' | 'misleading' | 'unverified') | null;
  };
  /**
   * Template: Issue → Facts → Documents → Response → Ground reality → Public questions → Answer → Follow-up
   */
  investigation?: {
    issue?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    facts?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    documents?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    response?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    groundReality?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    publicQuestions?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    answer?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    followUp?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * समस्या → शिकायत → संबंधित विभाग → जवाब → कार्रवाई → परिणाम
   */
  tracker?:
    | {
        stage: 'problem' | 'complaint' | 'department' | 'response' | 'action' | 'result';
        date?: string | null;
        status?: ('done' | 'progress' | 'pending') | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as a badge on "Direct Question to Government" stories
   */
  questionStatus?: ('asked' | 'responded' | 'action') | null;
  /**
   * Ministry / department / official asked
   */
  askedTo?: string | null;
  /**
   * If this is a "Response received" / "Action taken" story, link the original question here. Links show on both pages.
   */
  followUpOf?: (number | null) | Article;
  /**
   * Documents Speak: attach PDFs/images with source and reference
   */
  documents?:
    | {
        file: number | Media;
        title?: string | null;
        /**
         * e.g. RTI reply, Govt order, Court record
         */
        source?: string | null;
        /**
         * Letter no. / RTI no. / date
         */
        reference?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * External news-portal item. Shown as a clearly marked "related news portal" card.
   */
  linkCard?: {
    url?: string | null;
    siteName?: string | null;
    description?: string | null;
    /**
     * Leave empty for a text-only card
     */
    imageUrl?: string | null;
  };
  /**
   * Newspaper layout. The Desk sets this from the template; change only to fix a layout.
   */
  layout?: {
    template?: ('1' | '2' | '3' | '4' | '5' | '6') | null;
    /**
     * Text columns in the e-paper (1–4). Blank = template default.
     */
    columns?: number | null;
    inEpaper?: boolean | null;
    /**
     * Pin to a page. Blank = automatic.
     */
    epaperPage?: number | null;
    /**
     * Order inside the edition (lower = earlier). Blank = automatic.
     */
    epaperOrder?: number | null;
    autoFit?: boolean | null;
    /**
     * Body text size in %. Auto Fit may lower it slightly, never below 90%.
     */
    bodyScale?: number | null;
    headlineSize?: ('sm' | 'md' | 'lg' | 'xl') | null;
    headlineInk?: ('default' | 'black' | 'navy' | 'red' | 'saffron' | 'green' | 'gray') | null;
    subheadlineSize?: ('sm' | 'md' | 'lg' | 'xl') | null;
    subheadlineInk?: ('default' | 'black' | 'navy' | 'red' | 'saffron' | 'green' | 'gray') | null;
    reporterSize?: ('sm' | 'md' | 'lg' | 'xl') | null;
    reporterInk?: ('default' | 'black' | 'navy' | 'red' | 'saffron' | 'green' | 'gray') | null;
    align?: ('left' | 'center' | 'justify') | null;
    photoSize?: ('s' | 'm' | 'l' | 'full') | null;
    photoPos?: ('top' | 'left' | 'right') | null;
  };
  /**
   * URL. Blank = auto from title. Roman letters recommended (e.g. kisan-mandi-bhav).
   */
  slug?: string | null;
  format: 'news' | 'factcheck' | 'investigation' | 'question' | 'tracker' | 'documents' | 'opinion' | 'link' | 'video';
  category: number | Category;
  tags?: (number | Tag)[] | null;
  /**
   * Legacy byline (use Reporter below)
   */
  author?: (number | null) | Author;
  /**
   * Reporter / correspondent shown in the byline
   */
  reporterName?: string | null;
  /**
   * Optional: link to a team profile
   */
  reporter?: (number | null) | TeamMember;
  /**
   * Dateline, e.g. पटना
   */
  location?: string | null;
  /**
   * Permanent News ID (auto, at first publish)
   */
  newsId?: string | null;
  /**
   * Original publish time. Never changes.
   */
  firstPublishedAt?: string | null;
  /**
   * Future date = scheduled; goes live automatically.
   */
  publishedAt: string;
  heroImage?: (number | null) | Media;
  /**
   * Made from this news (Desk → Social share). Edit before sharing; the link and News ID are always added.
   */
  social?: {
    headline?: string | null;
    description?: string | null;
    hashtags?: string | null;
  };
  /**
   * ONE approved script: the red FLASH strip and the female voice both use exactly this text. The system never adds facts.
   */
  flash?: {
    enabled?: boolean | null;
    /**
     * Short, factual — written and approved by the editor.
     */
    script?: string | null;
    breaking?: boolean | null;
    repeat?: boolean | null;
    /**
     * Repeat interval (seconds)
     */
    intervalSec?: number | null;
    voice?: boolean | null;
    /**
     * Speed (1 = normal)
     */
    voiceRate?: number | null;
    /**
     * Voice volume %
     */
    voiceVolume?: number | null;
    /**
     * Pause between sentences (ms)
     */
    pauseMs?: number | null;
    audioUrl?: string | null;
    /**
     * Cache key: script + voice settings
     */
    audioKey?: string | null;
    approvedBy?: string | null;
    approvedAt?: string | null;
  };
  /**
   * Video news: the uploaded video (website version, social versions, flash + voice).
   */
  video?: (number | null) | Video;
  /**
   * Only for freely-licensed hotlinked images (Wikimedia/Unsplash). Credit is required.
   */
  externalImage?: {
    url?: string | null;
    credit?: string | null;
    creditUrl?: string | null;
  };
  featured?: boolean | null;
  reviewStatus?: ('draft' | 'submitted' | 'changes' | 'approved') | null;
  legalReviewed?: boolean | null;
  sample?: boolean | null;
  /**
   * Temporary demo item. Bulk delete: npm run demo:remove
   */
  demoContent?: boolean | null;
  createdBy?: (number | null) | User;
  /**
   * Archive / Delete / Restore from the Desk (/desk/news).
   */
  lifecycle?: ('active' | 'archived' | 'trashed') | null;
  lifecycleBefore?: string | null;
  trashedAt?: string | null;
  trashReason?: string | null;
  /**
   * Version = 1.<this>. Goes up on every change to a published story.
   */
  versionMinor?: number | null;
  /**
   * Latest (re-)publish time.
   */
  lastPublishedAt?: string | null;
  lastEditedBy?: string | null;
  /**
   * Optional public note for this edit (shown as “संशोधित”). Not stored on the story itself.
   */
  editNote?: string | null;
  /**
   * Public edit log (auto).
   */
  revisions?:
    | {
        at: string;
        note?: string | null;
        locale?: string | null;
        by?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images and public documents (PDF). Always fill credit + licence for third-party files.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * e.g. "Photo: Jane Doe / Unsplash"
   */
  credit?: string | null;
  creditUrl?: string | null;
  /**
   * e.g. CC BY-SA 4.0, Unsplash License, Own
   */
  license?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL. Blank = auto from title. Roman letters recommended (e.g. kisan-mandi-bhav).
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Set for sub-categories
   */
  parent?: (number | null) | Category;
  /**
   * Main menu position (lower = first). Sub-categories are ordered the same way.
   */
  menuOrder?: number | null;
  showInMenu?: boolean | null;
  /**
   * Column in the desktop mega-menu
   */
  menuGroup?: ('news' | 'accountability' | 'public' | 'people') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  /**
   * URL. Blank = auto from title. Roman letters recommended (e.g. kisan-mandi-bhav).
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * URL. Blank = auto from title. Roman letters recommended (e.g. kisan-mandi-bhav).
   */
  slug?: string | null;
  designation?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  /**
   * Linked login (optional)
   */
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'senior' | 'editor' | 'reporter';
  /**
   * Untick to stop this Editor from publishing. Admins always can. Reporters can never publish.
   */
  canPublish?: boolean | null;
  /**
   * Untick (Admin only) to reset this person’s authenticator app — they will scan a new QR at next login.
   */
  totpEnabled?: boolean | null;
  totpSecret?: string | null;
  totpLast?: number | null;
  totpFails?: number | null;
  totpLockUntil?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Save as draft → click Preview → then Publish. Only Editors/Admins can add or change profiles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * URL. Blank = auto from title. Roman letters recommended (e.g. kisan-mandi-bhav).
   */
  slug?: string | null;
  photo?: (number | null) | Media;
  /**
   * As shown publicly, e.g. "राज्य ब्यूरो प्रमुख, बिहार"
   */
  designation: string;
  /**
   * Decides the group and the order on the Team page.
   */
  tier:
    | 'editor-in-chief'
    | 'editorial'
    | 'state-bureau'
    | 'assistant-bureau'
    | 'special-correspondent'
    | 'reporter'
    | 'photographer'
    | 'other';
  /**
   * कार्यक्षेत्र, e.g. "पटना और आसपास के ज़िले"
   */
  workArea?: string | null;
  state?:
    | (
        | 'Andaman and Nicobar Islands'
        | 'Andhra Pradesh'
        | 'Arunachal Pradesh'
        | 'Assam'
        | 'Bihar'
        | 'Chandigarh'
        | 'Chhattisgarh'
        | 'Dadra and Nagar Haveli and Daman and Diu'
        | 'Delhi'
        | 'Goa'
        | 'Gujarat'
        | 'Haryana'
        | 'Himachal Pradesh'
        | 'Jammu and Kashmir'
        | 'Jharkhand'
        | 'Karnataka'
        | 'Kerala'
        | 'Ladakh'
        | 'Lakshadweep'
        | 'Madhya Pradesh'
        | 'Maharashtra'
        | 'Manipur'
        | 'Meghalaya'
        | 'Mizoram'
        | 'Nagaland'
        | 'Odisha'
        | 'Puducherry'
        | 'Punjab'
        | 'Rajasthan'
        | 'Sikkim'
        | 'Tamil Nadu'
        | 'Telangana'
        | 'Tripura'
        | 'Uttar Pradesh'
        | 'Uttarakhand'
        | 'West Bengal'
      )
    | null;
  district?: string | null;
  /**
   * Bureau / office
   */
  bureau?: string | null;
  /**
   * Press / ID card number
   */
  idNumber?: string | null;
  bio?: string | null;
  /**
   * Experience / specialisation (optional)
   */
  experience?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Off by default. Contact details are shown on the site only if this is ticked.
   */
  publishContact?: boolean | null;
  /**
   * Lower = earlier within the same group.
   */
  order?: number | null;
  /**
   * Sample profile (removed by npm run demo:remove)
   */
  demoContent?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Tip: the Desk (/desk/video) uploads videos in a few clicks; the logo is added automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  /**
   * URL. Blank = auto from title. Roman letters recommended (e.g. kisan-mandi-bhav).
   */
  slug?: string | null;
  description?: string | null;
  location?: string | null;
  /**
   * Date of the event (not the publish time)
   */
  eventDate?: string | null;
  reporterName?: string | null;
  reporter?: (number | null) | TeamMember;
  category?: (number | null) | Category;
  /**
   * Optional. Blank = a frame from the video is used.
   */
  thumbnail?: (number | null) | Media;
  /**
   * The untouched upload. Kept separately; never overwritten.
   */
  originalUrl?: string | null;
  /**
   * Logo-watermarked copy that is published.
   */
  processedUrl?: string | null;
  posterUrl?: string | null;
  processing?: ('queued' | 'processing' | 'ready' | 'failed') | null;
  processError?: string | null;
  durationSec?: number | null;
  sizeBytes?: number | null;
  width?: number | null;
  height?: number | null;
  hasAudio?: boolean | null;
  /**
   * Social-Ready 1920×1080 (headline, News ID, date, reporter, end screen)
   */
  socialUrl?: string | null;
  /**
   * Social-Ready vertical 1080×1920
   */
  verticalUrl?: string | null;
  /**
   * Final video with Flash strip + voice
   */
  flashUrl?: string | null;
  /**
   * Replaced videos are kept here (never deleted).
   */
  previousFiles?:
    | {
        originalUrl?: string | null;
        processedUrl?: string | null;
        replacedAt?: string | null;
        by?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The master news record (News ID, QR, publish state) this video belongs to.
   */
  article?: (number | null) | Article;
  /**
   * Future date = scheduled.
   */
  publishedAt?: string | null;
  demoContent?: boolean | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breaking-news".
 */
export interface BreakingNew {
  id: number;
  text: string;
  /**
   * Optional, e.g. /hi/news/some-slug
   */
  link?: string | null;
  active?: boolean | null;
  expiresAt?: string | null;
  demoContent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections".
 */
export interface Correction {
  id: number;
  article: number | Article;
  type?: ('correction' | 'clarification' | 'update') | null;
  date: string;
  /**
   * What was wrong and what was corrected
   */
  summary: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL. Blank = auto from title. Roman letters recommended (e.g. kisan-mandi-bhav).
   */
  slug?: string | null;
  /**
   * Optional photo (e.g. the Editor-in-Chief for the message page)
   */
  image?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  legalReviewPending?: boolean | null;
  showInFooter?: boolean | null;
  /**
   * Feature this page as a block on the home page (used for the Editor-in-Chief’s message).
   */
  showOnHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  anonymous?: boolean | null;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  state?: string | null;
  district?: string | null;
  location?: string | null;
  issueType?: string | null;
  department?: string | null;
  subject?: string | null;
  description?: string | null;
  complaintFiled?: string | null;
  complaintRef?: string | null;
  files?: (number | PrivateFile)[] | null;
  referenceId?: string | null;
  status?: ('new' | 'verifying' | 'story-in-progress' | 'published' | 'closed' | 'spam') | null;
  internalNotes?: string | null;
  consentAt?: string | null;
  lang?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Files attached by citizens. Not publicly accessible.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-files".
 */
export interface PrivateFile {
  id: number;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: number;
  name?: string | null;
  organisation?: string | null;
  phone?: string | null;
  email?: string | null;
  state?: string | null;
  city?: string | null;
  meetingWith?: string | null;
  purpose?: string | null;
  preferredDate?: string | null;
  preferredTime?: string | null;
  mode?: string | null;
  message?: string | null;
  referenceId?: string | null;
  status?: ('new' | 'confirmed' | 'rescheduled' | 'declined' | 'done') | null;
  internalNotes?: string | null;
  consentAt?: string | null;
  lang?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  topic?: string | null;
  subject?: string | null;
  message?: string | null;
  referenceId?: string | null;
  status?: ('new' | 'replied' | 'closed' | 'spam') | null;
  internalNotes?: string | null;
  consentAt?: string | null;
  lang?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * हर ज़रूरी कार्रवाई का स्थायी रिकॉर्ड। इसे बदला या मिटाया नहीं जा सकता।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  action: string;
  summary?: string | null;
  newsId?: string | null;
  articleId?: number | null;
  collectionSlug?: string | null;
  title?: string | null;
  url?: string | null;
  user?: (number | null) | User;
  userName?: string | null;
  role?: string | null;
  fromStatus?: string | null;
  toStatus?: string | null;
  reason?: string | null;
  version?: string | null;
  changedFields?: string | null;
  ip?: string | null;
  /**
   * Short fingerprint of the login session (never the token itself).
   */
  session?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-jobs".
 */
export interface MediaJob {
  id: number;
  kind: 'web' | 'social' | 'vertical' | 'flash';
  video: number | Video;
  status?: ('queued' | 'running' | 'done' | 'failed') | null;
  attempts?: number | null;
  lockedAt?: string | null;
  error?: string | null;
  params?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * आवाज़ में सही उच्चारण के लिए। खबर का दिखने वाला पाठ नहीं बदलता।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pronunciations".
 */
export interface Pronunciation {
  id: number;
  /**
   * As written in the news, e.g. झामुमो
   */
  word: string;
  /**
   * How the voice should say it, e.g. झारखंड मुक्ति मोर्चा
   */
  speakAs: string;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "share-log".
 */
export interface ShareLog {
  id: number;
  article?: (number | null) | Article;
  newsId?: string | null;
  title?: string | null;
  kind?: ('news' | 'video' | 'epaper') | null;
  platform: string;
  status: 'queued' | 'success' | 'failed';
  /**
   * Sent automatically on publish
   */
  auto?: boolean | null;
  postUrl?: string | null;
  response?: string | null;
  attempts?: number | null;
  by?: string | null;
  /**
   * What was posted (headline, text, link, media)
   */
  item?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads".
 */
export interface Ad {
  id: number;
  /**
   * Advertiser / internal name (also the image alt text)
   */
  title: string;
  /**
   * Portrait works best for the e-paper column (e.g. 600×900).
   */
  image: number | Media;
  /**
   * Optional website of the advertiser
   */
  link?: string | null;
  placements: ('epaper' | 'home-top' | 'article')[];
  active?: boolean | null;
  startsAt?: string | null;
  endsAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'breaking-news';
        value: number | BreakingNew;
      } | null)
    | ({
        relationTo: 'corrections';
        value: number | Correction;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'appointments';
        value: number | Appointment;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'private-files';
        value: number | PrivateFile;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'media-jobs';
        value: number | MediaJob;
      } | null)
    | ({
        relationTo: 'pronunciations';
        value: number | Pronunciation;
      } | null)
    | ({
        relationTo: 'share-log';
        value: number | ShareLog;
      } | null)
    | ({
        relationTo: 'ads';
        value: number | Ad;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  subheadline?: T;
  excerpt?: T;
  content?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  factCheck?:
    | T
    | {
        claim?: T;
        claimedBy?: T;
        verdict?: T;
      };
  investigation?:
    | T
    | {
        issue?: T;
        facts?: T;
        documents?: T;
        response?: T;
        groundReality?: T;
        publicQuestions?: T;
        answer?: T;
        followUp?: T;
      };
  tracker?:
    | T
    | {
        stage?: T;
        date?: T;
        status?: T;
        note?: T;
        id?: T;
      };
  questionStatus?: T;
  askedTo?: T;
  followUpOf?: T;
  documents?:
    | T
    | {
        file?: T;
        title?: T;
        source?: T;
        reference?: T;
        id?: T;
      };
  linkCard?:
    | T
    | {
        url?: T;
        siteName?: T;
        description?: T;
        imageUrl?: T;
      };
  layout?:
    | T
    | {
        template?: T;
        columns?: T;
        inEpaper?: T;
        epaperPage?: T;
        epaperOrder?: T;
        autoFit?: T;
        bodyScale?: T;
        headlineSize?: T;
        headlineInk?: T;
        subheadlineSize?: T;
        subheadlineInk?: T;
        reporterSize?: T;
        reporterInk?: T;
        align?: T;
        photoSize?: T;
        photoPos?: T;
      };
  slug?: T;
  format?: T;
  category?: T;
  tags?: T;
  author?: T;
  reporterName?: T;
  reporter?: T;
  location?: T;
  newsId?: T;
  firstPublishedAt?: T;
  publishedAt?: T;
  heroImage?: T;
  social?:
    | T
    | {
        headline?: T;
        description?: T;
        hashtags?: T;
      };
  flash?:
    | T
    | {
        enabled?: T;
        script?: T;
        breaking?: T;
        repeat?: T;
        intervalSec?: T;
        voice?: T;
        voiceRate?: T;
        voiceVolume?: T;
        pauseMs?: T;
        audioUrl?: T;
        audioKey?: T;
        approvedBy?: T;
        approvedAt?: T;
      };
  video?: T;
  externalImage?:
    | T
    | {
        url?: T;
        credit?: T;
        creditUrl?: T;
      };
  featured?: T;
  reviewStatus?: T;
  legalReviewed?: T;
  sample?: T;
  demoContent?: T;
  createdBy?: T;
  lifecycle?: T;
  lifecycleBefore?: T;
  trashedAt?: T;
  trashReason?: T;
  versionMinor?: T;
  lastPublishedAt?: T;
  lastEditedBy?: T;
  editNote?: T;
  revisions?:
    | T
    | {
        at?: T;
        note?: T;
        locale?: T;
        by?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  location?: T;
  eventDate?: T;
  reporterName?: T;
  reporter?: T;
  category?: T;
  thumbnail?: T;
  originalUrl?: T;
  processedUrl?: T;
  posterUrl?: T;
  processing?: T;
  processError?: T;
  durationSec?: T;
  sizeBytes?: T;
  width?: T;
  height?: T;
  hasAudio?: T;
  socialUrl?: T;
  verticalUrl?: T;
  flashUrl?: T;
  previousFiles?:
    | T
    | {
        originalUrl?: T;
        processedUrl?: T;
        replacedAt?: T;
        by?: T;
        id?: T;
      };
  article?: T;
  publishedAt?: T;
  demoContent?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  parent?: T;
  menuOrder?: T;
  showInMenu?: T;
  menuGroup?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  designation?: T;
  bio?: T;
  photo?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  designation?: T;
  tier?: T;
  workArea?: T;
  state?: T;
  district?: T;
  bureau?: T;
  idNumber?: T;
  bio?: T;
  experience?: T;
  email?: T;
  phone?: T;
  publishContact?: T;
  order?: T;
  demoContent?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breaking-news_select".
 */
export interface BreakingNewsSelect<T extends boolean = true> {
  text?: T;
  link?: T;
  active?: T;
  expiresAt?: T;
  demoContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections_select".
 */
export interface CorrectionsSelect<T extends boolean = true> {
  article?: T;
  type?: T;
  date?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  content?: T;
  legalReviewPending?: T;
  showInFooter?: T;
  showOnHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  creditUrl?: T;
  license?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  anonymous?: T;
  name?: T;
  phone?: T;
  email?: T;
  state?: T;
  district?: T;
  location?: T;
  issueType?: T;
  department?: T;
  subject?: T;
  description?: T;
  complaintFiled?: T;
  complaintRef?: T;
  files?: T;
  referenceId?: T;
  status?: T;
  internalNotes?: T;
  consentAt?: T;
  lang?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  name?: T;
  organisation?: T;
  phone?: T;
  email?: T;
  state?: T;
  city?: T;
  meetingWith?: T;
  purpose?: T;
  preferredDate?: T;
  preferredTime?: T;
  mode?: T;
  message?: T;
  referenceId?: T;
  status?: T;
  internalNotes?: T;
  consentAt?: T;
  lang?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  topic?: T;
  subject?: T;
  message?: T;
  referenceId?: T;
  status?: T;
  internalNotes?: T;
  consentAt?: T;
  lang?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-files_select".
 */
export interface PrivateFilesSelect<T extends boolean = true> {
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  canPublish?: T;
  totpEnabled?: T;
  totpSecret?: T;
  totpLast?: T;
  totpFails?: T;
  totpLockUntil?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  action?: T;
  summary?: T;
  newsId?: T;
  articleId?: T;
  collectionSlug?: T;
  title?: T;
  url?: T;
  user?: T;
  userName?: T;
  role?: T;
  fromStatus?: T;
  toStatus?: T;
  reason?: T;
  version?: T;
  changedFields?: T;
  ip?: T;
  session?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-jobs_select".
 */
export interface MediaJobsSelect<T extends boolean = true> {
  kind?: T;
  video?: T;
  status?: T;
  attempts?: T;
  lockedAt?: T;
  error?: T;
  params?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pronunciations_select".
 */
export interface PronunciationsSelect<T extends boolean = true> {
  word?: T;
  speakAs?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "share-log_select".
 */
export interface ShareLogSelect<T extends boolean = true> {
  article?: T;
  newsId?: T;
  title?: T;
  kind?: T;
  platform?: T;
  status?: T;
  auto?: T;
  postUrl?: T;
  response?: T;
  attempts?: T;
  by?: T;
  item?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads_select".
 */
export interface AdsSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  link?: T;
  placements?: T;
  active?: T;
  startsAt?: T;
  endsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Line under the site name (header, footer, e-paper masthead), e.g. “आधिकारिक ई-पेपर और डिजिटल न्यूज़”.
   */
  descriptor?: string | null;
  tagline?: string | null;
  trustName?: string | null;
  trustRegistrationNo?: string | null;
  editorName?: string | null;
  publisherName?: string | null;
  /**
   * Any other legal / registration text for the footer
   */
  registrationNote?: string | null;
  /**
   * Shown on the Contact page and in the footer. WhatsApp numbers also appear in the floating WhatsApp button.
   */
  offices?:
    | {
        /**
         * e.g. पंजीकृत कार्यालय
         */
        title: string;
        address?: string | null;
        /**
         * Optional second line, e.g. ऑनलाइन समाचारपत्र एवं डिजिटल न्यूज़ प्रकोष्ठ …
         */
        unit?: string | null;
        phones?:
          | {
              number: string;
              kind?: ('both' | 'whatsapp' | 'call') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Pre-filled text when a visitor opens WhatsApp from the site.
   */
  whatsappMessage?: string | null;
  whatsappButton?: boolean | null;
  /**
   * Old single address (used only when no offices are listed above).
   */
  address?: string | null;
  email?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  grievanceOfficer?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  /**
   * New submissions / appointments / contact messages are emailed here (falls back to NOTIFY_EMAIL env).
   */
  notifyEmail?: string | null;
  social?: {
    facebook?: string | null;
    x?: string | null;
    youtube?: string | null;
    instagram?: string | null;
    whatsappChannel?: string | null;
    telegram?: string | null;
  };
  /**
   * Set once. Applied automatically to every uploaded video (the original file is kept untouched).
   */
  videoWatermark?: {
    enabled?: boolean | null;
    position?: ('tr' | 'tl' | 'br' | 'bl') | null;
    /**
     * Logo width as % of the video width
     */
    sizePercent?: number | null;
    /**
     * Logo opacity in %
     */
    opacity?: number | null;
    /**
     * Distance from the edge, as % of the video width
     */
    marginPercent?: number | null;
    /**
     * Optional PNG with transparent background. Blank = the official round logo.
     */
    logo?: (number | null) | Media;
  };
  aiVoiceNote?: boolean | null;
  /**
   * Platform keys live in the server environment (see .env.example). A platform without keys stays OFF and the Desk offers Copy caption + Download media + Open platform instead. Failed posts never block publishing.
   */
  autoShare?: {
    news?: boolean | null;
    video?: boolean | null;
    epaper?: boolean | null;
    /**
     * Which platforms auto-share may use (only those with keys actually post).
     */
    platforms?: ('telegram' | 'facebook' | 'instagram' | 'x')[] | null;
    /**
     * Always added to posts
     */
    hashtags?: string | null;
  };
  /**
   * Show ads from Content → Advertisements (e-paper column, home page, story pages). Off = no ads anywhere.
   */
  adsEnabled?: boolean | null;
  /**
   * Placeholder only — not built yet.
   */
  donationsEnabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * प्रधान संपादक / एडमिन के पास हमेशा सभी अधिकार रहते हैं। बाकी भूमिकाओं के अधिकार यहां बदलें; बदलाव लगभग 30 सेकंड में हर जगह लागू होते हैं।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: number;
  publish?: {
    reporter?: boolean | null;
    editor?: boolean | null;
    senior?: boolean | null;
  };
  approve?: {
    reporter?: boolean | null;
    editor?: boolean | null;
    senior?: boolean | null;
  };
  editOthers?: {
    reporter?: boolean | null;
    editor?: boolean | null;
    senior?: boolean | null;
  };
  download?: {
    reporter?: boolean | null;
    editor?: boolean | null;
    senior?: boolean | null;
  };
  share?: {
    reporter?: boolean | null;
    editor?: boolean | null;
    senior?: boolean | null;
  };
  archive?: {
    reporter?: boolean | null;
    editor?: boolean | null;
    senior?: boolean | null;
  };
  republish?: {
    reporter?: boolean | null;
    editor?: boolean | null;
    senior?: boolean | null;
  };
  restore?: {
    reporter?: boolean | null;
    editor?: boolean | null;
    senior?: boolean | null;
  };
  versionHistory?: {
    reporter?: boolean | null;
    editor?: boolean | null;
    senior?: boolean | null;
  };
  trashOwnDraft?: {
    reporter?: boolean | null;
    editor?: boolean | null;
    senior?: boolean | null;
  };
  trashPublished?: {
    reporter?: boolean | null;
    editor?: boolean | null;
    senior?: boolean | null;
  };
  trashVideo?: {
    reporter?: boolean | null;
    editor?: boolean | null;
    senior?: boolean | null;
  };
  auditLog?: {
    reporter?: boolean | null;
    editor?: boolean | null;
    senior?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  descriptor?: T;
  tagline?: T;
  trustName?: T;
  trustRegistrationNo?: T;
  editorName?: T;
  publisherName?: T;
  registrationNote?: T;
  offices?:
    | T
    | {
        title?: T;
        address?: T;
        unit?: T;
        phones?:
          | T
          | {
              number?: T;
              kind?: T;
              id?: T;
            };
        id?: T;
      };
  whatsappMessage?: T;
  whatsappButton?: T;
  address?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  grievanceOfficer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  notifyEmail?: T;
  social?:
    | T
    | {
        facebook?: T;
        x?: T;
        youtube?: T;
        instagram?: T;
        whatsappChannel?: T;
        telegram?: T;
      };
  videoWatermark?:
    | T
    | {
        enabled?: T;
        position?: T;
        sizePercent?: T;
        opacity?: T;
        marginPercent?: T;
        logo?: T;
      };
  aiVoiceNote?: T;
  autoShare?:
    | T
    | {
        news?: T;
        video?: T;
        epaper?: T;
        platforms?: T;
        hashtags?: T;
      };
  adsEnabled?: T;
  donationsEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  publish?:
    | T
    | {
        reporter?: T;
        editor?: T;
        senior?: T;
      };
  approve?:
    | T
    | {
        reporter?: T;
        editor?: T;
        senior?: T;
      };
  editOthers?:
    | T
    | {
        reporter?: T;
        editor?: T;
        senior?: T;
      };
  download?:
    | T
    | {
        reporter?: T;
        editor?: T;
        senior?: T;
      };
  share?:
    | T
    | {
        reporter?: T;
        editor?: T;
        senior?: T;
      };
  archive?:
    | T
    | {
        reporter?: T;
        editor?: T;
        senior?: T;
      };
  republish?:
    | T
    | {
        reporter?: T;
        editor?: T;
        senior?: T;
      };
  restore?:
    | T
    | {
        reporter?: T;
        editor?: T;
        senior?: T;
      };
  versionHistory?:
    | T
    | {
        reporter?: T;
        editor?: T;
        senior?: T;
      };
  trashOwnDraft?:
    | T
    | {
        reporter?: T;
        editor?: T;
        senior?: T;
      };
  trashPublished?:
    | T
    | {
        reporter?: T;
        editor?: T;
        senior?: T;
      };
  trashVideo?:
    | T
    | {
        reporter?: T;
        editor?: T;
        senior?: T;
      };
  auditLog?:
    | T
    | {
        reporter?: T;
        editor?: T;
        senior?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}